CREATE PROCEDURE INSERT_IMAGES_PRODUCT

    @IMAGES_PRODUCT_NAME NVARCHAR(MAX),
    @IMAGES_PRODUCT_DATA VARBINARY(MAX),
    @IMAGES_PRODUCT_ENABLE BIT,
    @IMAGES_PRODUCT_DESCRIPTION NVARCHAR(150),
    @IMAGES_PRODUCT_USER NVARCHAR(100),
    @IMAGES_PRODUCT_LAST_USER NVARCHAR(100),
    @IMAGES_PRODUCT_DATE DATETIME = NULL,
    @IMAGES_PRODUCT_LAST_DATE DATETIME = NULL
AS
BEGIN

    INSERT INTO IMAGES_PRODUCT (
        IMAGES_PRODUCT_NAME,
        IMAGES_PRODUCT_DATA,
        IMAGES_PRODUCT_ENABLE,
        IMAGES_PRODUCT_DESCRIPTION,
        IMAGES_PRODUCT_USER,
        IMAGES_PRODUCT_LAST_USER,
        IMAGES_PRODUCT_DATE,
        IMAGES_PRODUCT_LAST_DATE
    )
    VALUES (
        @IMAGES_PRODUCT_NAME,
        @IMAGES_PRODUCT_DATA,
        @IMAGES_PRODUCT_ENABLE,
        @IMAGES_PRODUCT_DESCRIPTION,
        @IMAGES_PRODUCT_USER,
        @IMAGES_PRODUCT_LAST_USER,
        @IMAGES_PRODUCT_DATE,
        @IMAGES_PRODUCT_LAST_DATE
    );
END;
