CREATE PROCEDURE SELECT_IMAGES_PRODUCTS
    @IMAGES_PRODUCT_NAME NVARCHAR(MAX)
AS
BEGIN
    SELECT 
        IMAGES_PRODUCT_ID,
        IMAGES_PRODUCT_NAME,
        IMAGES_PRODUCT_DATA,
        IMAGES_PRODUCT_ENABLE,
        IMAGES_PRODUCT_DESCRIPTION,
        IMAGES_PRODUCT_USER,
        IMAGES_PRODUCT_LAST_USER,
        IMAGES_PRODUCT_DATE,
        IMAGES_PRODUCT_LAST_DATE
    FROM 
        IMAGES_PRODUCT
    WHERE 
        IMAGES_PRODUCT_NAME = @IMAGES_PRODUCT_NAME;
END;
