CREATE PROCEDURE UPDATE_IMAGES_PRODUCTS
    @IMAGES_PRODUCT_ID INT,
    @IMAGES_PRODUCT_NAME NVARCHAR(MAX),
    @IMAGES_PRODUCT_DATA NVARCHAR(MAX),
    @IMAGES_PRODUCT_ENABLE BIT,
    @IMAGES_PRODUCT_DESCRIPTION NVARCHAR(150),
    @IMAGES_PRODUCT_USER NVARCHAR(100),
    @IMAGES_PRODUCT_LAST_USER NVARCHAR(100)
AS
BEGIN
    UPDATE IMAGES_PRODUCT
    SET 
        IMAGES_PRODUCT_NAME = @IMAGES_PRODUCT_NAME,
        IMAGES_PRODUCT_DATA = @IMAGES_PRODUCT_DATA,
        IMAGES_PRODUCT_ENABLE = @IMAGES_PRODUCT_ENABLE,
        IMAGES_PRODUCT_DESCRIPTION = @IMAGES_PRODUCT_DESCRIPTION,
        IMAGES_PRODUCT_USER = @IMAGES_PRODUCT_USER,
        IMAGES_PRODUCT_LAST_USER = @IMAGES_PRODUCT_LAST_USER,
        IMAGES_PRODUCT_DATE = GETDATE(), -- Actualiza con la fecha y hora actual
        IMAGES_PRODUCT_LAST_DATE = GETDATE() -- Actualiza con la fecha y hora actual
    WHERE 
        IMAGES_PRODUCT_ID = @IMAGES_PRODUCT_ID;
END;
