CREATE TABLE [ANIMALS] (
  [ANIMALS_ID] uniqueidentifier NOT NULL DEFAULT(NEWID()),
  [ANIMALS_DESCRIPTION] NVARCHAR(100) NOT NULL,
  [ANIMALS_USER] NVARCHAR(50) NOT NULL,
  [ANIMALS_DATE] datetime NOT NULL DEFAULT((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'Central Standard Time'),
  [ANIMALS_ENABLE] BIT NOT NULL,
  [ANIMALS_NAME] NVARCHAR(50),
  [ANIMALS_TYPE] NVARCHAR(50) NOT NULL,
  [ANIMALS_OLDDATE] NVARCHAR(50) NOT NULL,
  PRIMARY KEY ([ANIMALS_ID])
);