CREATE TABLE CATEGORY (
  CATEGORY_ID INT PRIMARY KEY,
  CATEGORY_NAME NVARCHAR(100) NOT NULL,
  CATEGORY_ENABLE BIT, 
  CATEGORY_USER NVARCHAR(100),
  CATEGORY_LAST_USER NVARCHAR(100),
  CATEGORY_DATE DATETIME DEFAULT GETDATE(),
  CATEGORY_LAST_DATE DATETIME DEFAULT GETDATE()
);