CREATE TABLE IMAGES_PRODUCT (
  IMAGES_PRODUCT_ID INT IDENTITY(1,1) PRIMARY KEY,
  IMAGES_PRODUCT_NAME NVARCHAR(MAX) NOT NULL,
  IMAGES_PRODUCT_DATA NVARCHAR(MAX), 
  IMAGES_PRODUCT_ENABLE BIT, 
  IMAGES_PRODUCT_DESCRIPTION NVARCHAR(150),
  IMAGES_PRODUCT_USER NVARCHAR(100),
  IMAGES_PRODUCT_LAST_USER NVARCHAR(100),
  IMAGES_PRODUCT_DATE DATETIME DEFAULT GETDATE(),
  IMAGES_PRODUCT_LAST_DATE DATETIME DEFAULT GETDATE()
);