CREATE TABLE [IMAGES] (
  [IMAGE_ID] uniqueidentifier NOT NULL DEFAULT(NEWID()),
  [ANIMALS_ID] uniqueidentifier NOT NULL,
  [IMAGE_DESCRIPTION] NVARCHAR(150) NOT NULL,
  [IMAGE_USER] NVARCHAR(50) NOT NULL,
  [IMAGE_DATE] datetime NOT NULL DEFAULT((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'Central Standard Time'),
  [IMAGE_DATA] BIT NOT NULL,
  [IMAGE_URL] NVARCHAR(MAX) NOT NULL,
  PRIMARY KEY ([IMAGE_ID]),
  CONSTRAINT [FK_IMAGES.ANIMALS_ID]
    FOREIGN KEY ([ANIMALS_ID])
      REFERENCES [ANIMALS]([ANIMALS_ID])
);