CREATE TABLE [TYPE_USER] (
  [TYPE_USER_ID] uniqueidentifier NOT NULL DEFAULT(NEWID()),
  [TYPE_USER_DESCRIPTION] NVARCHAR(150) NOT NULL,
  [TYPE_USER_REGISTER] NVARCHAR(50) NOT NULL,
  [TYPE_USER_DATE] datetime NOT NULL DEFAULT((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'Central Standard Time'),
  PRIMARY KEY ([TYPE_USER_ID])
);
