CREATE TABLE [USER_GORA] (
  [USER_GORA] NVARCHAR(50) NOT NULL,
  [TYPE_USER_ID] uniqueidentifier NOT NULL ,
  [USER_ECOMMERCE_COGNITO] uniqueidentifier NOT NULL,
  PRIMARY KEY ([USER_GORA]),
  CONSTRAINT [FK_USER_GORA.TYPE_USER_ID]
    FOREIGN KEY ([TYPE_USER_ID])
      REFERENCES [TYPE_USER]([TYPE_USER_ID])
);