CREATE PROCEDURE INSERT_PRODUCTS

    @PRODUCTS_NAME NVARCHAR(100),
    @PRODUCTS_DESCRIPTION NVARCHAR(100),
    @PRODUCTS_WORTH FLOAT,
    @PRODUCTS_STOCK INT,
    @PRODUCTS_ENABLE BIT,
    @CATEGORY_ID INT,
    @PRODUCTS_USER NVARCHAR(100),
    @PRODUCTS_LAST_USER NVARCHAR(100),
    @PRODUCTS_DATE DATETIME = NULL,
    @PRODUCTS_LAST_DATE DATETIME = NULL
AS
BEGIN
    INSERT INTO PRODUCTS (
        PRODUCTS_NAME,
        PRODUCTS_DESCRIPTION,
        PRODUCTS_WORTH,
        PRODUCTS_STOCK,
        PRODUCTS_ENABLE,
        CATEGORY_ID,
        PRODUCTS_USER,
        PRODUCTS_LAST_USER,
        PRODUCTS_DATE,
        PRODUCTS_LAST_DATE
    )
    VALUES (
        @PRODUCTS_NAME,
        @PRODUCTS_DESCRIPTION,
        @PRODUCTS_WORTH,
        @PRODUCTS_STOCK,
        @PRODUCTS_ENABLE,
        @CATEGORY_ID,
        @PRODUCTS_USER,
        @PRODUCTS_LAST_USER,
        @PRODUCTS_DATE,
        @PRODUCTS_LAST_DATE
    );

END;
