CREATE PROCEDURE SELECT_PRODUCTS

    @PRODUCTS_NAME NVARCHAR(100)
AS
BEGIN

    SELECT 
        PRODUCTS_ID,
        PRODUCTS_NAME,
        PRODUCTS_DESCRIPTION,
        PRODUCTS_WORTH,
        PRODUCTS_STOCK,
        PRODUCTS_ENABLE,
        CATEGORY_ID,
        PRODUCTS_USER,
        PRODUCTS_LAST_USER,
        PRODUCTS_DATE,
        PRODUCTS_LAST_DATE
    FROM 
        PRODUCTS
    WHERE 
        PRODUCTS_NAME = @PRODUCTS_NAME;
END;
