CREATE PROCEDURE UPDATE_PRODUCTS

    @PRODUCTS_ID INT,                
    @PRODUCTS_NAME NVARCHAR(100),    
    @PRODUCTS_DESCRIPTION NVARCHAR(150),
    @PRODUCTS_WORTH FLOAT,            
    @PRODUCTS_STOCK INT,              
    @PRODUCTS_ENABLE BIT,            
    @CATEGORY_ID INT,                 
    @PRODUCTS_LAST_USER NVARCHAR(100) 
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE PRODUCTS
    SET 
        PRODUCTS_NAME = @PRODUCTS_NAME,
        PRODUCTS_DESCRIPTION = @PRODUCTS_DESCRIPTION,
        PRODUCTS_WORTH = @PRODUCTS_WORTH,
        PRODUCTS_STOCK = @PRODUCTS_STOCK,
        PRODUCTS_ENABLE = @PRODUCTS_ENABLE,
        CATEGORY_ID = @CATEGORY_ID,
        PRODUCTS_LAST_USER = @PRODUCTS_LAST_USER,
        PRODUCTS_LAST_DATE = GETDATE()
    WHERE 
        PRODUCTS_ID = @PRODUCTS_ID; 
END;
