CREATE PROCEDURE INSERT_CATEGORY
    @CATEGORY_NAME NVARCHAR(100),
    @CATEGORY_ENABLE BIT,
    @CATEGORY_USER NVARCHAR(100),
    @CATEGORY_LAST_USER NVARCHAR(100)
AS
BEGIN
    INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_ENABLE, CATEGORY_USER, CATEGORY_LAST_USER, CATEGORY_DATE, CATEGORY_LAST_DATE)
    VALUES (@CATEGORY_NAME, @CATEGORY_ENABLE, @CATEGORY_USER, @CATEGORY_LAST_USER, GETDATE(), GETDATE());
    

END
