CREATE PROCEDURE UPDATE_CATEGORY
    @ID INT,
    @CATEGORY_NAME NVARCHAR(100),
    @CATEGORY_ENABLE BIT,
    @CATEGORY_USER NVARCHAR(100),
    @CATEGORY_LAST_USER NVARCHAR(100)
AS
BEGIN
    UPDATE CATEGORY
    SET 
        CATEGORY_NAME = @CATEGORY_NAME,
        CATEGORY_ENABLE = @CATEGORY_ENABLE,
        CATEGORY_USER = @CATEGORY_USER,
        CATEGORY_LAST_USER = @CATEGORY_LAST_USER,
        CATEGORY_LAST_DATE = GETDATE()  -- Fecha de la última actualización
    WHERE ID = @ID;

END
